[project]
name = "ai-testing"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "langgraph>=0.2.0",
    "langchain-core>=1.1.0",
    "langchain-openai>=0.2.0",
    "python-dotenv>=1.2.1",
    "streamlit>=1.52.0",
]
